name: Clojure CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Producce Coverage Report
      run: lein cloverage --codecov
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v1
    - name: Lein jar
      run: lein uberjar
